##======- Makefile --------------------------------------*- Makefile -*-======##
##===----------------------------------------------------------------------===##
PROJECT_NAME = RangeAnalysis
LIBRARYNAME = RangeAnalysis
LOADABLE_MODULE = 1
USEDLIBS =
LEVEL = .
LLVM_SRC_ROOT = /Users/fernando/Programs/llvm37
LLVM_OBJ_ROOT = /Users/fernando/Programs/llvm37/build
PROJ_SRC_ROOT = .
PROJ_OBJ_ROOT = .
PROJ_INSTALL_ROOT = /Users/fernando/Programs/llvm37/build/lib/..
include $(LLVM_OBJ_ROOT)/Makefile.config
CXXFLAGS += -std=c++0x -Wno-deprecated-declarations -fexceptions -Wall -Wextra
include $(LLVM_SRC_ROOT)/Makefile.rules
